version: '3.5'

services:
  openthink_backend:
    image: openthink_backend:latest
    container_name: openthink_backend
    env_file: docker.env
    depends_on:
      - db
    ports:
      - "4000:4000"
