export const attributes = [
    'Text',
    'Number',
    'Select',
    'Multi-select',
    'Date',
    'Person',
    'Attachment',
    'Checkbox',
    'URL',
    'Email',
    'Phone',
    'Currency',
    'Percent',
    'Duration',
    'Rating',
    'Formula',
    'Relation',
    'Rollup',
    'Space',
    'Lookup',
    'Count',
    'Barcode',
    'Button',
    'Autonumber',
    'Created By',
    'Created Time',
    'Last Edited Time',
    'Last Edited By',
]
